version: '3.8'

services:
  # FastAPI Application only - connects to existing local databases
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Application Configuration
      - APP_NAME=ResXiv
      - APP_VERSION=1.0.0
      - APP_DESCRIPTION=Unified Research Collaboration Platform
      - ENVIRONMENT=production
      - DEBUG=false
      - SECRET_KEY=your-super-secure-secret-key-change-this-in-production
      
      # JWT Configuration
      - JWT_SECRET_KEY=your-super-secure-jwt-secret-key-change-this-in-production
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - JWT_REFRESH_TOKEN_EXPIRE_DAYS=7
      
      # Server Configuration
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=4
      - RELOAD=false
      
      # Database Configuration - PostgreSQL
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - POSTGRES_DB=resxiv
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_ECHO=false
      - POSTGRES_POOL_SIZE=10
      - POSTGRES_MAX_OVERFLOW=20
      
      # Database Configuration - MongoDB
      - MONGODB_HOST=host.docker.internal
      - MONGODB_PORT=27017
      - MONGODB_DB=resxiv_chat
      - MONGODB_USER=
      - MONGODB_PASSWORD=
      - MONGODB_REPLICA_SET=
      
      # Redis Configuration
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
      - REDIS_SOCKET_TIMEOUT=30
      - REDIS_CONNECTION_POOL_SIZE=10
      
      # CORS Configuration
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,https://dev.resxiv.com,https://www.dev.resxiv.com
      - CORS_CREDENTIALS=true
      - CORS_METHODS=GET,POST,PUT,DELETE,OPTIONS,PATCH
      
    volumes:
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads
      - ./static:/app/static
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway" 