version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend/resxiv_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=demo-secret-key-for-investors-2024
      - JWT_SECRET_KEY=demo-jwt-secret-key-2024
      - ENVIRONMENT=production
      - DEBUG=false
      - CORS_ORIGINS=http://localhost:3000,https://cbeta.resxiv.com,http://cbeta.resxiv.com
      - DATABASE_URL=postgresql://resxiv_user:resxiv_password@postgres:5432/resxiv_db
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://mongodb:27017/resxiv_chat
    depends_on:
      - postgres
      - mongodb
      - redis
    volumes:
      - ./backend/resxiv_backend/uploads:/app/uploads
      - ./backend/resxiv_backend/downloads:/app/downloads
      - ./backend/resxiv_backend/static:/app/static
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=resxiv_db
      - POSTGRES_USER=resxiv_user
      - POSTGRES_PASSWORD=resxiv_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_export.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  mongodb:
    image: mongo:6
    environment:
      - MONGO_INITDB_DATABASE=resxiv_chat
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb_dump:/docker-entrypoint-initdb.d/dump
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  mongodb_data:
  redis_data: 